nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
#       '^/bands/all/':
#           allow_origin: ['^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
#            allow_headers: ['X-Custom-Auth', 'Content-type']
#            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#            max_age: 3600
       '^/':
            origin_regex: true
            allow_origin: ['^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
            allow_headers: ['X-Custom-Auth', 'Content-type']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
